module.exports = [{
    "value": "上海市",
    "label": "上海市",
    "children": [{
        "value": "上海市",
        "label": "上海市",
        "children": [{
            "value": "黄浦区",
            "label": "黄浦区",
            "children": []
        }, {
            "value": "卢湾区",
            "label": "卢湾区",
            "children": []
        }, {
            "value": "徐汇区",
            "label": "徐汇区",
            "children": []
        }, {
            "value": "长宁区",
            "label": "长宁区",
            "children": []
        }, {
            "value": "静安区",
            "label": "静安区",
            "children": []
        }, {
            "value": "普陀区",
            "label": "普陀区",
            "children": []
        }, {
            "value": "闸北区",
            "label": "闸北区",
            "children": []
        }, {
            "value": "虹口区",
            "label": "虹口区",
            "children": []
        }, {
            "value": "杨浦区",
            "label": "杨浦区",
            "children": []
        }, {
            "value": "宝山区",
            "label": "宝山区",
            "children": []
        }, {
            "value": "闵行区",
            "label": "闵行区",
            "children": []
        }, {
            "value": "嘉定区",
            "label": "嘉定区",
            "children": []
        }, {
            "value": "松江区",
            "label": "松江区",
            "children": []
        }, {
            "value": "金山区",
            "label": "金山区",
            "children": []
        }, {
            "value": "青浦区",
            "label": "青浦区",
            "children": []
        }, {
            "value": "奉贤区",
            "label": "奉贤区",
            "children": []
        }, {
            "value": "浦东新区",
            "label": "浦东新区",
            "children": []
        }, {
            "value": "崇明县",
            "label": "崇明县",
            "children": []
        }, {
            "value": "其他",
            "label": "其他",
            "children": []
        }]
    }]
}];